export const POOL_CONTENT_ITEM = 'POOL_CONTENT_ITEM';
export const QUEST_CONTENT_ITEM = 'QUEST_CONTENT_ITEM';
export const QUEST_CONTENT_AREA = 'QUEST_CONTENT_AREA';
export const CONTENT_POOL = 'CONTENT_POOL';
