---
platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: "6"}
run:
  path: sh
  args:
    - -exec
    - |
      cp culture-client-master/* culture-client-master-installed -r
      cp culture-client-master/.git culture-client-master-installed -r
      cp culture-client-master/.gitignore culture-client-master-installed -r
      cp culture-client-master/.dockerignore culture-client-master-installed -r
      cd culture-client-master-installed
      npm install
inputs:
  - name: culture-client-master
outputs:
  - name: culture-client-master-installed
